language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
script:
- pytest tests/test_sample.py
- pyflakes .
- pep8 --statistics --count .

matrix:
  fast_finish: true